name: "Deploy with Shuttle"
description: "Deploy code to production server using cargo-shuttle"
author: "HyperCodec"
branding:
  icon: "truck"
  color: "orange-red"
inputs:
  api_key:
    description: "API key for Shuttle account"
    required: true
  project_name:
    description: "The name of the Shuttle project"
  path:
    description: "The path to your shuttle project"
runs:
  using: "node16"
  main: main.js
