name: Add latest tag on release

on: [release]

permissions:
    contents: write

jobs:
    add-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EndBug/latest-tag@latest