name: Add latest tag on release

on: [release]

jobs:
    add-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EndBug/latest-tag@latest
              with:
                description: Points to the latest release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}