name: Add latest tag on release

on: [release, pull_request]

jobs:
    add-tag:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: EndBug/latest-tag@latest